# Generated by Django 4.0.6 on 2022-08-23 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_item_rest_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
