# Generated by Django 4.0.6 on 2022-12-03 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
